{{/*
Expand the name of the chart.
*/}}
{{- define "butler-portal.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "butler-portal.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "butler-portal.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "butler-portal.labels" -}}
helm.sh/chart: {{ include "butler-portal.chart" . }}
{{ include "butler-portal.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "butler-portal.selectorLabels" -}}
app.kubernetes.io/name: {{ include "butler-portal.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "butler-portal.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "butler-portal.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
CNPG cluster name
*/}}
{{- define "butler-portal.dbClusterName" -}}
{{- printf "%s-db" (include "butler-portal.fullname" .) }}
{{- end }}

{{/*
CNPG app secret name (auto-generated by CNPG)
*/}}
{{- define "butler-portal.dbSecretName" -}}
{{- printf "%s-app" (include "butler-portal.dbClusterName" .) }}
{{- end }}
