{{/*
Expand the name of the chart.
*/}}
{{- define "butler-portal.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "butler-portal.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "butler-portal.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "butler-portal.labels" -}}
helm.sh/chart: {{ include "butler-portal.chart" . }}
{{ include "butler-portal.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "butler-portal.selectorLabels" -}}
app.kubernetes.io/name: {{ include "butler-portal.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "butler-portal.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "butler-portal.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
CNPG cluster name
*/}}
{{- define "butler-portal.dbClusterName" -}}
{{- printf "%s-db" (include "butler-portal.fullname" .) }}
{{- end }}

{{/*
CNPG app secret name (auto-generated by CNPG)
*/}}
{{- define "butler-portal.dbSecretName" -}}
{{- printf "%s-app" (include "butler-portal.dbClusterName" .) }}
{{- end }}

{{/*
Guard: for every entry in .Values.dynamicPlugins.plugins that sets
permissions.enforced=true, require its permissions.pluginId to be
present in .Values.permission.rbac.pluginsWithPermission.

Why: RBAC does not auto-discover plugin permissions. A plugin whose
id is not listed under permission.rbac.pluginsWithPermission returns
[] from the discovery API and enforcement silently passes through —
authorize() returns ALLOW regardless of policy. Documenting the
requirement four times has not been enough; this helper turns the
misconfiguration into a helm template failure at install/upgrade so
the missing wiring cannot ship to a running cluster.

Opt-in per plugin. Plugins that don't set permissions.enforced=true
are ignored (backward compatible for existing values files and for
purely-UI dynamic plugins that declare no permissions).
*/}}
{{- define "butler-portal.validateRbacPluginsWithPermission" -}}
{{- $listed := .Values.permission.rbac.pluginsWithPermission | default (list) -}}
{{- range $p := .Values.dynamicPlugins.plugins -}}
  {{- if and $p.permissions $p.permissions.enforced -}}
    {{- if not $p.permissions.pluginId -}}
      {{- fail (printf "dynamicPlugins.plugins entry %q sets permissions.enforced=true but omits permissions.pluginId; the guard cannot check the wiring without knowing which plugin id to look for. Add permissions.pluginId: <the pluginId the plugin registers as>." (default "<unnamed>" $p.package)) -}}
    {{- end -}}
    {{- if not (has $p.permissions.pluginId $listed) -}}
      {{- fail (printf "dynamicPlugins.plugins entry %q declares permissions.enforced=true with pluginId %q, but permission.rbac.pluginsWithPermission does not include %q. Without this entry, RBAC returns [] from its discovery API for this plugin and every authorize() call silently passes through as ALLOW regardless of policy. Add %q to permission.rbac.pluginsWithPermission." (default "<unnamed>" $p.package) $p.permissions.pluginId $p.permissions.pluginId $p.permissions.pluginId) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end }}

{{/*
Warn-loudly on plugin entries that opt OUT of the structural guard.

Detection at helm-template time is not possible: the chart cannot read
an OCI plugin's manifest to know whether the plugin declares
permissions, so the guard is opt-in per plugin. But opt-in has an
inherent gap — the adopters who would forget the pluginsWithPermission
listing are the same adopters who would forget to opt into the guard.

This helper fires a NOTES.txt warning on every plugin entry that does
not opt in. The warning names the CONSEQUENCE (RBAC enforcement is OFF
for this plugin if it declares permissions, and its gated writes pass
through as ALLOW), not the omission (consider opting in). The framing
matters: without it, the warning reads as a lint nit; with it, the
warning reads as "your authz is not running."

Renders empty when every plugin entry has permissions.enforced=true or
when dynamicPlugins.plugins is empty.
*/}}
{{- define "butler-portal.warnRbacUnopted" -}}
{{- $unopted := list -}}
{{- range $p := .Values.dynamicPlugins.plugins -}}
  {{- if not (and $p.permissions $p.permissions.enforced) -}}
    {{- $unopted = append $unopted (default "<unnamed>" $p.package) -}}
  {{- end -}}
{{- end -}}
{{- if gt (len $unopted) 0 }}

WARNING: pluginsWithPermission enforcement is OFF for {{ len $unopted }} plugin entr{{ if eq (len $unopted) 1 }}y{{ else }}ies{{ end }}.

If any of the plugins listed below declares Backstage permissions,
their authz is NOT running: RBAC has no rule to evaluate for them and
their gated writes pass-through as ALLOW regardless of your policy CSV.

{{ range $unopted }}  - {{ . }}
{{ end }}
Set `permissions.enforced: true` and `permissions.pluginId: <id>` on
each plugin entry to structurally enforce the pluginsWithPermission
listing at helm install/upgrade. The guard is opt-in because the
chart cannot read OCI plugin manifests to auto-detect which plugins
declare permissions; the opt-in is your assertion that the plugin does.

If a plugin does NOT declare permissions (purely-UI plugins, frontend
widgets, etc.), leaving this unset is correct — this warning applies
only when a listed plugin gates anything via `permissions.authorize()`
inside its backend.
{{- end -}}
{{- end }}
