---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-admins
  title: Platform Administrators
  description: Registry platform administrators with full cross-team access
spec:
  type: role
  children: []
  members: [founder]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  title: Platform Engineering Team
  description: Butler Labs platform engineering
spec:
  type: team
  children: []
  members: [founder, user:development/guest]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team-admins
  title: Platform Team Admins
spec:
  type: role
  children: []
  members: [founder]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team-operators
  title: Platform Team Operators
spec:
  type: role
  children: []
  members: [user:development/guest]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team
  title: Development Team
  description: Butler Labs application development
spec:
  type: team
  children: []
  members: [founder, user:development/guest]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team-operators
  title: Dev Team Operators
spec:
  type: role
  children: []
  members: [user:development/guest]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: founder
  title: Andrew Bagan
spec:
  memberOf: [platform-admins, platform-team, platform-team-admins, dev-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: development
  name: guest
  title: Guest User
spec:
  memberOf: [platform-team, platform-team-operators, dev-team, dev-team-operators]

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infrastructure
  title: Infrastructure
  description: Core infrastructure and platform services
spec:
  owner: group:default/platform-team

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: butler-kaas
  title: Butler KaaS Platform
  description: Kubernetes-as-a-Service platform for multi-tenant cluster management
  tags:
    - kubernetes
    - platform
    - infrastructure
  links:
    - url: https://github.com/butlerdotdev/butler
      title: GitHub Repository
      icon: github
spec:
  owner: group:default/platform-team
  domain: infrastructure

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: butler-management-cluster
  title: Management Cluster
  description: Central management cluster running Kamaji, Flux, and platform controllers
  tags:
    - kubernetes
    - talos
    - management
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: butler-kaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cilium-cni
  title: Cilium CNI
  description: eBPF-based networking and security
  tags:
    - networking
    - cni
spec:
  type: resource
  owner: group:default/platform-team
  system: butler-kaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: linstor-storage
  title: LINSTOR Storage
  description: Distributed block storage via Piraeus/LINSTOR
  tags:
    - storage
    - csi
spec:
  type: resource
  owner: group:default/platform-team
  system: butler-kaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: flux-gitops
  title: FluxCD
  description: GitOps continuous delivery
  tags:
    - gitops
    - flux
spec:
  type: resource
  owner: group:default/platform-team
  system: butler-kaas
