apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: butler-portal
  description: Internal developer portal powered by Backstage
spec:
  type: website
  owner: group:default/butlerlabs
  lifecycle: production
