// Copyright 2026 The Butler Authors.
// SPDX-License-Identifier: Apache-2.0

import { resolveRoutePermission } from './routeAuthorization';

// Every authenticated butler-server route (internal/api/router.go at
// v0.22.0) with the permission the proxy must require. Keep this list in
// step with the server; an unmapped route is denied by the proxy.
const cases: Array<[string, string, string | undefined]> = [
  ['GET', '/auth/me', 'butler.team.read'],
  ['GET', '/auth/teams', 'butler.team.read'],
  ['POST', '/auth/logout', 'butler.team.read'],
  ['POST', '/auth/refresh-permissions', 'butler.team.read'],
  ['POST', '/auth/cli/approve', 'butler.team.read'],
  ['GET', '/auth/ssh-keys', 'butler.workspace.read'],
  ['POST', '/auth/ssh-keys', 'butler.workspace.manage'],
  ['DELETE', '/auth/ssh-keys/SHA256:abc', 'butler.workspace.manage'],
  ['POST', '/auth/login', undefined],
  ['POST', '/auth/login/legacy', undefined],
  ['GET', '/auth/invite/tok', undefined],
  ['POST', '/auth/cli/device', undefined],

  ['GET', '/clusters', 'butler.cluster.read'],
  ['GET', '/clusters?team=alpha', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/nodes', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/events', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/export', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/machines', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/load-balancers', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/tenantcontrolplane', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/addons', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/addons/cilium', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/certificates', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/certificates/ca', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/certificates/rotation-status', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/gitops/status', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/gitops/discover', 'butler.cluster.read'],
  ['GET', '/clusters/ns/c1/kubeconfig', 'butler.cluster.kubeconfig'],
  ['POST', '/clusters', 'butler.cluster.create'],
  ['PUT', '/clusters/ns/c1', 'butler.cluster.update'],
  ['PATCH', '/clusters/ns/c1/scale', 'butler.cluster.update'],
  ['PUT', '/clusters/ns/c1/environment', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/settings/workspaces', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/addons', 'butler.cluster.update'],
  ['PUT', '/clusters/ns/c1/addons/cilium', 'butler.cluster.update'],
  ['DELETE', '/clusters/ns/c1/addons/cilium', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/certificates/rotate', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/gitops/enable', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/gitops/export-cluster', 'butler.cluster.update'],
  ['POST', '/clusters/ns/c1/gitops/preview-cluster', 'butler.cluster.update'],
  ['DELETE', '/clusters/ns/c1/gitops', 'butler.cluster.update'],
  ['DELETE', '/clusters/ns/c1', 'butler.cluster.delete'],

  ['GET', '/clusters/ns/c1/workspaces', 'butler.workspace.read'],
  ['GET', '/clusters/ns/c1/workspaces/ws1', 'butler.workspace.read'],
  ['GET', '/clusters/ns/c1/workspaces/ws1/metrics', 'butler.workspace.read'],
  ['GET', '/clusters/ns/c1/services', 'butler.workspace.read'],
  ['POST', '/clusters/ns/c1/mirrord-config', 'butler.workspace.read'],
  ['POST', '/clusters/ns/c1/workspaces', 'butler.workspace.manage'],
  ['DELETE', '/clusters/ns/c1/workspaces/ws1', 'butler.workspace.manage'],
  ['POST', '/clusters/ns/c1/workspaces/ws1/connect', 'butler.workspace.manage'],
  ['POST', '/clusters/ns/c1/workspaces/ws1/sync-ssh-keys', 'butler.workspace.manage'],
  ['GET', '/workspace-images', 'butler.workspace.read'],
  ['GET', '/workspace-templates', 'butler.workspace.read'],
  ['POST', '/workspace-templates', 'butler.workspace.manage'],
  ['DELETE', '/workspace-templates/ns/t1', 'butler.workspace.manage'],

  ['GET', '/addons/catalog', 'butler.cluster.read'],
  ['GET', '/addons/catalog/cilium', 'butler.cluster.read'],
  ['GET', '/gitops/config', 'butler.cluster.read'],
  ['GET', '/gitops/repos', 'butler.cluster.read'],
  ['GET', '/gitops/repos/branches?repo=a/b', 'butler.cluster.read'],
  ['POST', '/gitops/config', 'butler.admin.manage'],
  ['DELETE', '/gitops/config', 'butler.admin.manage'],
  ['POST', '/gitops/preview', 'butler.admin.manage'],
  ['GET', '/observability/config', 'butler.cluster.read'],

  ['GET', '/teams', 'butler.team.read'],
  ['GET', '/teams/alpha', 'butler.team.read'],
  ['GET', '/teams/alpha/clusters', 'butler.team.read'],
  ['GET', '/teams/alpha/members', 'butler.team.read'],
  ['GET', '/teams/alpha/groups', 'butler.team.read'],
  ['GET', '/teams/alpha/audit', 'butler.team.read'],
  ['GET', '/teams/alpha/providers', 'butler.team.read'],
  ['GET', '/users', 'butler.team.read'],
  ['POST', '/teams', 'butler.team.manage'],
  ['PUT', '/teams/alpha', 'butler.team.manage'],
  ['DELETE', '/teams/alpha', 'butler.team.manage'],
  ['POST', '/teams/alpha/providers', 'butler.team.manage'],
  ['POST', '/teams/alpha/providers/test', 'butler.team.manage'],
  ['DELETE', '/teams/alpha/providers/ns/p1', 'butler.team.manage'],
  ['POST', '/teams/alpha/environments', 'butler.team.manage'],
  ['PUT', '/teams/alpha/environments/dev', 'butler.team.manage'],
  ['DELETE', '/teams/alpha/environments/dev', 'butler.team.manage'],
  ['POST', '/admin/teams/alpha/members', 'butler.team.manage'],
  ['PATCH', '/admin/teams/alpha/members/a%40b.com', 'butler.team.manage'],
  ['DELETE', '/admin/teams/alpha/members/a%40b.com', 'butler.team.manage'],
  ['POST', '/admin/teams/alpha/groups', 'butler.team.manage'],
  ['PATCH', '/admin/teams/alpha/groups/g1', 'butler.team.manage'],
  ['DELETE', '/admin/teams/alpha/groups/g1', 'butler.team.manage'],
  ['POST', '/admin/teams', 'butler.admin.manage'],
  ['DELETE', '/admin/teams/alpha', 'butler.admin.manage'],

  ['GET', '/providers', 'butler.provider.read'],
  ['GET', '/providers/ns/p1', 'butler.provider.read'],
  ['GET', '/providers/ns/p1/images', 'butler.provider.read'],
  ['GET', '/providers/ns/p1/networks', 'butler.provider.read'],
  ['GET', '/providers/ns/p1/clusters', 'butler.provider.read'],
  ['GET', '/providers/ns/p1/storage-containers', 'butler.provider.read'],
  ['GET', '/providers/ns/p1/ca-info', 'butler.provider.read'],
  ['POST', '/providers', 'butler.provider.manage'],
  ['POST', '/providers/test', 'butler.provider.manage'],
  ['PUT', '/providers/ns/p1', 'butler.provider.manage'],
  ['DELETE', '/providers/ns/p1', 'butler.provider.manage'],
  ['POST', '/providers/ns/p1/validate', 'butler.provider.manage'],

  ['GET', '/management', 'butler.admin.read'],
  ['GET', '/management/nodes', 'butler.admin.read'],
  ['GET', '/management/pods/butler-system', 'butler.admin.read'],
  ['GET', '/management/addons', 'butler.admin.read'],
  ['GET', '/management/gitops/status', 'butler.admin.read'],
  ['GET', '/management/tenantcontrolplanes', 'butler.admin.read'],
  ['GET', '/management/datastores/default', 'butler.admin.read'],
  ['POST', '/management/addons', 'butler.admin.manage'],
  ['DELETE', '/management/addons/steward', 'butler.admin.manage'],
  ['POST', '/management/gitops/enable', 'butler.admin.manage'],
  ['POST', '/management/gitops/export-cluster', 'butler.admin.manage'],
  ['DELETE', '/management/gitops', 'butler.admin.manage'],
  ['GET', '/image-syncs', 'butler.admin.read'],
  ['GET', '/image-factory/catalog', 'butler.admin.read'],
  ['POST', '/image-syncs', 'butler.admin.manage'],
  ['DELETE', '/image-syncs/ns/talos', 'butler.admin.manage'],

  ['GET', '/admin/identity-providers', 'butler.admin.read'],
  ['GET', '/admin/policies', 'butler.admin.read'],
  ['GET', '/admin/networks', 'butler.admin.read'],
  ['GET', '/admin/ipallocations', 'butler.admin.read'],
  ['GET', '/admin/config', 'butler.admin.read'],
  ['GET', '/admin/audit', 'butler.admin.read'],
  ['GET', '/admin/observability/status', 'butler.admin.read'],
  ['POST', '/admin/users', 'butler.admin.manage'],
  ['POST', '/admin/users/u1/invite', 'butler.admin.manage'],
  ['DELETE', '/admin/users/u1', 'butler.admin.manage'],
  ['POST', '/admin/identity-providers', 'butler.admin.manage'],
  ['PUT', '/admin/identity-providers/google', 'butler.admin.manage'],
  ['POST', '/admin/policies', 'butler.admin.manage'],
  ['POST', '/admin/addons/catalog', 'butler.admin.manage'],
  ['DELETE', '/admin/networks/ns/pool', 'butler.admin.manage'],
  ['DELETE', '/admin/ipallocations/ns/a1', 'butler.admin.manage'],
  ['PUT', '/admin/config', 'butler.admin.manage'],
  ['PUT', '/admin/observability/config', 'butler.admin.manage'],
  ['POST', '/admin/observability/pipeline/setup', 'butler.admin.manage'],

  ['WS', '/ws/clusters', 'butler.cluster.read'],
  ['WS', '/ws/terminal/management', 'butler.admin.manage'],
  ['WS', '/ws/terminal/tenant/ns/c1', 'butler.cluster.terminal'],
  ['WS', '/ws/terminal/tenant/ns/c1/pod/container', 'butler.cluster.terminal'],

  ['GET', '/_identity', undefined],
  ['GET', '/nope', undefined],
  ['POST', '/clusters/ns', undefined],
];

describe('resolveRoutePermission', () => {
  it.each(cases)('%s %s -> %s', (method, path, expected) => {
    expect(resolveRoutePermission(method, path)?.name).toBe(expected);
  });

  it('is case-insensitive on the method and ignores trailing slashes', () => {
    expect(resolveRoutePermission('get', '/clusters/')?.name).toBe(
      'butler.cluster.read',
    );
  });
});
